configure: Tighten checks around the hwloc library
Commit 698406aaf142 added the hwloc library as a dependency.  hwloc 1.x,
the original implementation, is not sufficient for our needs and causes
build errors like

  dlls/ntdll/unix/system.c: In function ‘traverse_hwloc_topology’:
  dlls/ntdll/unix/system.c:1406:10: error: ‘HWLOC_OBJ_L1CACHE’ undeclared
    (first use in this function); did you mean ‘HWLOC_OBJ_CACHE’?

So tighten our checks and not only look out for hwloc.h and libhwloc, but
also HWLOC_OBJ_L1CACHE in the former as an indication we are dealing with
a sufficiently new version.

This addresses
https://gitlab.winehq.org/wine/wine/-/merge_requests/7339#note_118432